[project]
name = "emma-cellpose-analysis"
version = "0.2.0"
description = "End-to-end multi-well plate colony segmentation using FastSAM and Cellpose"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    # AI Models & Dependencies
    "cellpose>=4.2.1.1",
    "torch>=2.1.2",
    "ultralytics>=8.1.0",
    "dinov3 @ git+https://github.com/facebookresearch/dinov3.git",
    "mobile-sam @ git+https://github.com/ChaoningZhang/MobileSAM.git",
    "timm",
    
    # Image Processing & Math
    "opencv-python>=4.9.0",
    "tifffile>=2024.1.30",
    "numpy>=1.26.0",
    
    # Data Export & Notebooks
    "pandas>=2.2.0",
    "jupyter>=1.0.0",
    
    # Under-the-hood fixes
    "packaging"
]

[tool.uv]
managed = true
dev-dependencies = []
